events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    # Server for abc.me
    server {
        listen 3000;
        server_name abc.me;

        location / {
            root /usr/share/nginx/html/abc.me;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
    }

    # Server for abc2.me
    server {
        listen 3000;
        server_name abc2.me;

        location / {
            root /usr/share/nginx/html/abc2.me;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
    }
}
